version: '3.4'

name: stone_employee

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: stone_employee
    ports:
      - "54320:5432"
    volumes:
      - postgres_data_stone_employee:/var/lib/postgresql/data

  stoneemployee.api:
    image: ${DOCKER_REGISTRY-}stoneemployeeapi
    build:
      context: .
      dockerfile: StoneEmployee.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__EmployeeConnectionString: "Host=postgres;Database=stone_employee;Username=postgres;Password=pass"
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - postgres

volumes:
  postgres_data_stone_employee: