// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoneEmployee.Infrastructure.Database;

#nullable disable

namespace StoneEmployee.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PgContext))]
    partial class PgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoneEmployee.Core.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("admission_data");

                    b.Property<string>("Document")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("document");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_salary");

                    b.Property<bool>("HasDentalPlan")
                        .HasColumnType("boolean")
                        .HasColumnName("has_dental_plan");

                    b.Property<bool>("HasHealthPlan")
                        .HasColumnType("boolean")
                        .HasColumnName("has_health_plan");

                    b.Property<bool>("HasTransportationVouchers")
                        .HasColumnType("boolean")
                        .HasColumnName("has_transportation_vouchers");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("Sector")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sector");

                    b.HasKey("Id");

                    b.ToTable("employee", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
